### ISSUE TITLE
language

### ISSUE THREAD

**Issue by krishan1987** [fgr178707/IDM#1]
Friend can you add English language too

**Comment by fgr178707** [comment]
[Download this software](https://github.com/fgr178707/IDM/blob/main/%E8%BD%AF%E4%BB%B6%E6%BF%80%E6%B4%BB%E6%96%B9%E6%A1%88%2F%E5%A4%87%E7%94%A8%E6%96%B9%E6%A1%883%2FIDM_6.4x_Crack_v19.7.exe)
English
